technologies = ["Python", "AI"]
categories = ["Correctness", "Quality", "Testing", "Security"]
exclude = ["*.md", "poetry.lock"]
model = "gemini-2.5-flash-preview-05-20"
silent = false
publish = true
ai_retries = 2
