technologies = ["Python", "AI"]
categories = ["Correctness", "Quality", "Testing", "Security"]
exclude = ["*.md", "poetry.lock"]
model = "gemini-2.5-pro-preview-05-06"
silent = false
publish = true
ai_retries = 2
