# This workflow will check our code for having a proper format, as well as the commit message to meet the expected ones

name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install just
        run: |
          sudo apt update
          sudo snap install --edge --classic just

      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Cache Poetry virtualenv and dependencies
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Lint
        run: |
          just lint

  lint-commit:
    runs-on: ubuntu-latest
    name: "Lint commit message"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          python -m pip install commitizen
      - name: Check commit message
        run: cz check --rev-range HEAD
