name: Publish

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  push_to_pypi:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  release_notes:
    runs-on: ubuntu-latest
    needs: push_to_pypi
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
